#pragma once

#define TARS_MOUSE_BUTTON_1 0
#define TARS_MOUSE_BUTTON_2 1
#define TARS_MOUSE_BUTTON_3 2
#define TARS_MOUSE_BUTTON_4 3
#define TARS_MOUSE_BUTTON_5 4
#define TARS_MOUSE_BUTTON_6 5
#define TARS_MOUSE_BUTTON_7 6
#define TARS_MOUSE_BUTTON_8 7
#define TARS_MOUSE_BUTTON_LAST TARS_MOUSE_BUTTON_8
#define TARS_MOUSE_BUTTON_LEFT TARS_MOUSE_BUTTON_1
#define TARS_MOUSE_BUTTON_RIGHT TARS_MOUSE_BUTTON_2
#define TARS_MOUSE_BUTTON_MIDDLE TARS_MOUSE_BUTTON_3